tunnel: garageos-dev
credentials-file: /Users/dibakar/.cloudflared/bbada279-60e9-4025-b6a1-17955c23a55b.json

ingress:

  # Public API routes
  - hostname: app.thegarageos.com
    service: http://192.168.0.170:80

  # Tenant subdomains
  - hostname: "*.thegarageos.com"
    service: http://192.168.0.170:80

  - service: http://192.168.0.170:80   # ← catch-all for custom domains